server:
  port: 9100   # your API Gateway port

spring:
  application:
    name: api-gateway

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/batch60
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update   # use update (create will delete tables every restart)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    

